CREATE DATABASE IF NOT EXISTS METADATA;

CREATE SCHEMA IF NOT EXISTS METADATA.SCHEMACHANGE;

CREATE TABLE IF NOT EXISTS METADATA.SCHEMACHANGE.CHANGE_HISTORY
(
    VERSION        VARCHAR,
    DESCRIPTION    VARCHAR,
    SCRIPT         VARCHAR,
    SCRIPT_TYPE    VARCHAR,
    CHECKSUM       VARCHAR,
    EXECUTION_TIME NUMBER,
    STATUS         VARCHAR,
    INSTALLED_BY   VARCHAR,
    INSTALLED_ON   TIMESTAMP_LTZ
)
