-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS CLEANSED;

CREATE SCHEMA IF NOT EXISTS REPORTING;

-- RAW schema tables
USE SCHEMA RAW;
CREATE TABLE IF NOT EXISTS LOCATION_DIRECTION_COUNTS (
    LOCATION_ID           NUMBER        NOT NULL,
    SENSING_DATETIME      TIMESTAMP_TZ  NOT NULL,
    DIRECTION_1           NUMBER        NOT NULL,
    DIRECTION_2           NUMBER        NOT NULL,
    TOTAL_OF_DIRECTIONS   NUMBER        NOT NULL
);

