name: deploy-database-schema-change-to-snowflake

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-database-schema-change:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWFLAKE_USERNAME: ${{ secrets.SF_USERNAME }}
      SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
      SNOWFLAKE_PRIVATE_KEY_FILE: /.ssh/snowflake_prod.p8
      SNOWFLAKE_PRIVATE_KEY_FILE_PWD: ${{ secrets.SF_PRIVATE_KEY_FILE_PWD }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.14.4
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.14.4


      - name: Install schemachange
        run: |
          pip --version
          echo "Step 1: Upgrade pip"
          pip install --upgrade pip
          echo "Step 2: Installing schemachange"          
          pip install schemachange==4.1.0

      - name: Run schemachange
        run: |
          
          echo "Creating temporary private key file..."

          # 1. Create the private key file from the secret
          echo "${{ secrets.SF_PRIVATE_KEY }}" > $SNOWFLAKE_PRIVATE_KEY_FILE
          chmod 600 $SNOWFLAKE_PRIVATE_KEY_FILE

          echo "Running schemachange..."

          # 2. Run the deployment
          schemachange deploy -f ./migrations \
            --schemachange-connections-file-path ./connections.toml \
            --schemachange-connection-name PROD \
            --create-change-history-table

      - name: Clean up private key file
        run: rm -f $SNOWFLAKE_PRIVATE_KEY_FILE